replicaCount: 2

image:
  repository: zapagendador
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000
  nodePort: 30085

env:
  NODE_ENV: "production"
  PORT: "3000"
  DATABASE_URL: "mysql://root:senha123@192.168.137.190:3306/zapagendador"
  OLLAMA_URL: "http://192.168.137.190:11434"
  JWT_SECRET: "chave-secreta-123"
  VITE_APP_ID: "meu-app-teste-123"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
